Component page template
js-tasks-ru/htmlcss-20210916_xoroshilov pull request #10
Opened 2021-09-28 21:51 UTC by khorosh1lov

Page template for components created

2021-09-28 21:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-29 19:29 UTC, GSemikozov requested changes

2021-09-29 19:29 UTC, GSemikozov commented on components/compopent-page.css
> +.component-page__content__title {
элемент элемента = ошибка. Можно .component-page__content-title

2021-09-29 19:29 UTC, GSemikozov commented on components/compopent-page.css
> +.component-page__footer__title {
.component-page__footer__title -> .component-page__footer-title

2021-09-29 20:27 UTC, khorosh1lov commented on components/compopent-page.css
> +.component-page__content__title {
Тут не совсем понял почему нейминг через -title

2021-09-29 20:27 UTC, khorosh1lov commented on components/compopent-page.css
> +.component-page__footer__title {
Тут не совсем понял почему нейминг через -title

2021-09-29 20:27 UTC, GSemikozov approved these changes

2021-09-29 20:27 UTC, merged

2021-09-29 20:28 UTC, khorosh1lov commented on components/compopent-page.css
> +.component-page__content__title {
Я его сделал конечно же и запушил, но не пойму почему мы делаем модификатор

2021-09-29 20:28 UTC, khorosh1lov commented on components/compopent-page.css
> +.component-page__footer__title {
Я его сделал конечно же и запушил, но не пойму почему мы делаем модификатор