histogram created based on Flexboxes
js-tasks-ru/htmlcss-20210916_xoroshilov pull request #6
Opened 2021-09-25 17:19 UTC by khorosh1lov

Histogram component created based on Flexboxes and BEM methodology

2021-09-25 17:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 12:20 UTC, GSemikozov requested changes

2021-09-26 12:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    background: #FFFFFF;
такой цвет есть в переменных)

2021-09-26 12:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header, .histogram__chart {
для .histogram__chart переопределяем ниже, поэтому - здесь задавать не надо

2021-09-26 12:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-evenly;
такой вариант выравнивания не подойдет (чтобы понять почему - советую оставить только 2 колонки в чарте =))

2021-09-26 12:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
по макету это 50 )

2021-09-26 12:20 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-right: 2px;
по макету - 1px

2021-09-26 16:41 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    background: #FFFFFF;
принял, пропустил

2021-09-26 16:43 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    height: fit-content;
Я сделал по контенту, так как ссылка занимает всю высоту блока, что конечно увеличивает площадь клика или тапа пальцем, но не совсем корректно и аккуратно. Ну ладно, сделаю по твоему )

2021-09-26 16:44 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header, .histogram__chart {
Окей, не хотелось дублировать общие свойства, но по БЭМ я так понял это никого не парит ))

2021-09-26 16:45 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
Окей, тут я сделал нагляднее просто

2021-09-26 16:45 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    margin-right: 2px;
поэтому я и сделал выше `justify-content: space-evenly;` хе-хе

2021-09-26 16:46 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
Понял, принял

2021-09-26 16:56 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-evenly;
Понял, это лишнее

2021-09-26 16:57 UTC, khorosh1lov commented on 04-lection2/01-histogram/histogram.css
> +    width: 100%;
Потестил и 1 и с 2 и с 50 колонками, теперь всё ок, да

2021-09-26 16:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-26 17:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-27 14:28 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: fit-content;
да не, все ок, но здесь важно еще и чтобы текст ссылки не переносился (если слева будет много контента, то ссылка сожмется, и не смотря на. то что там и так мало текста, она может быть в 2-3 строки и больше)

2021-09-27 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__header, .histogram__chart {
здесь дело в БЭМ а в лишним переопределении стилей)

2021-09-27 14:29 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 100px;
нам желательно по максимуму следовать дизайн макету)

2021-09-27 14:30 UTC, GSemikozov approved these changes

2021-09-27 14:30 UTC, merged